### PR TITLE
Support rack 2.0

### PR DESCRIPTION
**Pull request by gauravtiwari**

### CODE REVIEW

**Comment by jgorset** [comment]
I haven't tried Rack 2.0 yet. I guess it's backwards incompatible because it's a major version, but that it's compatible with the parts of Rack that we're using?

**Comment by frodsan** [comment]
@jgorset It's compatible. Rack 2.0 feels more like 1.7.

**Comment by gauravtiwari** [comment]
@jgorset yeah, it works with Rack we are using. Basically, Rails5 now uses rack 2.0 so, it would be good to support everything up to 2.0. `>= 1.64`

**Comment by jgorset** [comment]
Cool! Nice job!

**Pull request merged**
