### PR TITLE
Update to Graph API v20.0 and add new comment sending method

### PR DESCRIPTION
**Pull request by cvquez**
This pull request includes the following changes:

- Updated the library to use Graph API v20.0
- Added a new method for sending comments in the Bot module
- Incorporated changes from tviv fork:
  - Added feed event support
  - Added leadgen event support
  - Added standby entry support for Facebook Messenger

These updates will:
1. Keep our library current with the latest Facebook Graph API
2. Provide additional functionality for bot interactions, including improved handling of comments on Facebook posts
3. Expand event handling capabilities
4. Improve Facebook Messenger integration

The changes from the tviv fork enhance our library's ability to handle various Facebook events, improve Messenger functionality, and provide better support for interacting with comments on Facebook posts.

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks @cvquez! :sparkles: :cake: :sparkles: This is great.

**Comment by romiras** [comment]
Hey @jgorset , what about tag?

**Comment by thebravoman** [comment]
@jgorset do you plan of releasing the 2.1.2 version to rubygems?

**Comment by jgorset** [comment]
Sorry guys, I missed this for a long time! I added the tag and pushed 2.1.2 to Rubygems!

**Pull request merged**
