### PR TITLE
Implement messages and postbacks

### PR DESCRIPTION
**Pull request by jgorset**
TODO:

* [ ] Add tests for the controller

### CODE REVIEW

**Comment by sindrenm** [comment]
I've heard of this technique called “tests first”. Believe @fespinoza has some input. :trollface:

**Comment by jgorset** [comment]
HEHE FUNNY

**Comment by jgorset** [comment]
Actually that is pretty funny.

**Comment by jgorset** [comment]
A better approach than to bundle all sorts of integrations with this gem would be to make a gem for each framework (e.g. `facebook-messenger-rails`), so I'm closing this.

**Pull request closed without merging**
