### PR TITLE
unify directory name on Rails; bot -> bots

### PR DESCRIPTION
**Pull request by kuboon**
fix document error.

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Thanks @kuboon :+1:

**Comment by sindrenm** [comment]
This is such an easy mistake to make, so it's awesome that good people like you who notice it submit a PR, @kuboon. Thanks! :grinning:

**Comment by jgorset** [comment]
Well… I actually called it "bot" intentionally because there can only be one, but I'm fine with this change for convention's sake anyway. :wink:

**Comment by jgorset** [comment]
This is causing some confusion, so I reverted it in d7cc61e7178e83d32012b0ca4b8697e2dcb9c145.

**Pull request merged**
